### ISSUE TITLE
More specific data documentation/citations

### ISSUE THREAD

**Issue by rl2999** [spatialucr/geosnap#209] opened 2020-03-15 22:00 UTC
Hi there! First of all, wow!! I think this is an amazing package and I can't wait to see how it develops.

I was searching the documentation and I found it a bit unclear which data sources were being used for the Census, since they offer many different products (1, 3, 5 year, and decennial). It took a while to dig through the geosnap source in order to find a hint that it was pulling ACS data, and another search through API docs for cenpy to realize that it was ACS 5-year data. I think it would be helpful to note this somewhere in the documentation. 

I am also wondering if some explanation would be useful for the role of quilt—for ex: is the data being downloaded from https://open.quiltdata.com ? Is it being stored locally in a "quilt store?" Where is the "quilt store" located, and should I be concerned about disk space if it caches hundreds of MB to my small laptop SSD? I apologize if these seem like naive questions—I am a student learning urban data science.

**Comment by knaaptime** [comment] 2020-03-15 22:13
hey, thanks for this. These are all great questions. We're actually in the middle of a push to get the data documented better and I'll make a note to flesh out more of the details in the API docs as well (also, note we've just made a change to some of the formulas but i havent pushed a new dataset just yet).

It's also a good idea to add more documentation on quilt. `geosnap` tries to be conservative, so it will stream data from our [public bucket](https://open.quiltdata.com/b/spatial-ucr) without caching anything locally. If you want, though, you can also download and store the data locally using, e.g. `geosnap.io.store_census()`. The location is determined using [appdirs](https://pypi.org/project/appdirs/), so that would put a few hundred MBs likely in your user folder somewhere.

**Comment by knaaptime** [comment] 2020-04-12 16:21
duplicate of #68

**Comment by knaaptime** [comment] 2020-04-23 22:38
this should be resolved by #220 but let me know if https://spatialucr.github.io/geosnap/data is inadequate and we can reopen

**Closed by knaaptime** 2020-04-23 22:38 UTC
