### ISSUE TITLE
Harmonize returning nan for intensive variables

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/geosnap#249] opened 2020-08-06 21:08 UTC
```python
import geosnap
```

    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 17133.59entries/s]
    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 7020.93entries/s]

```python
geosnap.__version__
```

    '0.3.2'

```python
sd = geosnap.Community.from_census(county_fips='06073')
```

    /home/serge/anaconda3/envs/geosnapdev/lib/python3.7/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
      return _prepare_from_string(" ".join(pjargs))

```python
sd.gdf.head()
```

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>geoid</th>
      <th>n_mexican_pop</th>
      <th>n_cuban_pop</th>
      <th>n_puerto_rican_pop</th>
      <th>n_total_housing_units</th>
      <th>n_vacant_housing_units</th>
      <th>n_occupied_housing_units</th>
      <th>n_owner_occupied_housing_units</th>
      <th>n_renter_occupied_housing_units</th>
      <th>n_white_persons</th>
      <th>...</th>
      <th>p_irish_born_pop</th>
      <th>p_italian_born_pop</th>
      <th>p_poverty_rate_children</th>
      <th>p_poverty_rate_hispanic</th>
      <th>p_russian_born_pop</th>
      <th>p_scandanavian_born_pop</th>
      <th>p_scandanavian_pop</th>
      <th>n_total_pop_sample</th>
      <th>p_female_labor_force</th>
      <th>p_black_persons</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>5188</th>
      <td>06073019000</td>
      <td>5094.0</td>
      <td>2.0</td>
      <td>5.0</td>
      <td>2326.0</td>
      <td>184.0</td>
      <td>2142.0</td>
      <td>1769.0</td>
      <td>373.0</td>
      <td>4898911.0</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5189</th>
      <td>06073018700</td>
      <td>30479.0</td>
      <td>72.0</td>
      <td>611.0</td>
      <td>4819.0</td>
      <td>50.0</td>
      <td>4769.0</td>
      <td>250.0</td>
      <td>4519.0</td>
      <td>215361577.0</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5205</th>
      <td>06073019101</td>
      <td>2497.0</td>
      <td>0.0</td>
      <td>9.0</td>
      <td>1497.0</td>
      <td>154.0</td>
      <td>1343.0</td>
      <td>858.0</td>
      <td>485.0</td>
      <td>16221375.0</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5206</th>
      <td>06073020901</td>
      <td>4839.0</td>
      <td>7.0</td>
      <td>5.0</td>
      <td>3042.0</td>
      <td>995.0</td>
      <td>2047.0</td>
      <td>1430.0</td>
      <td>617.0</td>
      <td>4416241.0</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5207</th>
      <td>06073021000</td>
      <td>2337.0</td>
      <td>0.0</td>
      <td>15.0</td>
      <td>2457.0</td>
      <td>1154.0</td>
      <td>1303.0</td>
      <td>979.0</td>
      <td>324.0</td>
      <td>2302215.0</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 195 columns</p>
</div>

```python
extensive = ['n_total_pop', 'n_total_housing_units', 'n_vacant_housing_units']
intensive = ['median_household_income', 'p_poverty_rate']
```

```python
sd.gdf['median_household_income'] = sd.gdf['median_household_income'].fillna(0)
```

```python
sd.gdf['median_household_income'].isnull().sum()
```

    0

```python
sd.gdf['p_poverty_rate'] = sd.gdf['p_poverty_rate'].fillna(0)
```

```python
sd.gdf['p_poverty_rate'].isnull().sum()
```

    0

```python
sd_2010 = sd.harmonize(2010,extensive_variables=extensive,
                      intensive_variables=intensive)
```

    /home/serge/anaconda3/envs/geosnapdev/lib/python3.7/site-packages/tobler/area_weighted/area_weighted.py:249: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /home/serge/anaconda3/envs/geosnapdev/lib/python3.7/site-packages/tobler/area_weighted/area_weighted.py:249: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /home/serge/anaconda3/envs/geosnapdev/lib/python3.7/site-packages/tobler/area_weighted/area_weighted.py:249: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values

```python
sd_2010.gdf.head()
```

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>geoid</th>
      <th>geometry</th>
      <th>median_household_income</th>
      <th>n_total_housing_units</th>
      <th>n_total_pop</th>
      <th>n_vacant_housing_units</th>
      <th>p_poverty_rate</th>
      <th>year</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>06073014901</td>
      <td>POLYGON ((-117.01957 32.76373, -117.01562 32.7...</td>
      <td>NaN</td>
      <td>1876.000000</td>
      <td>4156.000000</td>
      <td>131.00000</td>
      <td>NaN</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>1</th>
      <td>06073000300</td>
      <td>POLYGON ((-117.16864 32.74897, -117.16602 32.7...</td>
      <td>NaN</td>
      <td>3046.000000</td>
      <td>4629.000000</td>
      <td>397.00000</td>
      <td>NaN</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>2</th>
      <td>06073000800</td>
      <td>POLYGON ((-117.14632 32.74842, -117.14250 32.7...</td>
      <td>NaN</td>
      <td>2702.000000</td>
      <td>3964.000000</td>
      <td>253.00000</td>
      <td>NaN</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>3</th>
      <td>06073002201</td>
      <td>POLYGON ((-117.11577 32.75522, -117.11362 32.7...</td>
      <td>NaN</td>
      <td>1321.000000</td>
      <td>3989.000000</td>
      <td>76.00000</td>
      <td>NaN</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>4</th>
      <td>06073018509</td>
      <td>POLYGON ((-117.37213 33.20012, -117.36902 33.2...</td>
      <td>NaN</td>
      <td>1700.999899</td>
      <td>5325.999683</td>
      <td>171.99999</td>
      <td>NaN</td>
      <td>2010</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by knaaptime** [comment] 2020-08-06 21:15
that's probably related to [this](https://github.com/pysal/tobler/pull/71) recent fix in tobler. I'll investigate

**Comment by sjsrey** [comment] 2020-08-06 21:20
Tobler seems ok. When I use the1990 and 2000 dataframes, the interpolation works for the intensive variables (with tobler not in geosnap)

![image](https://user-images.githubusercontent.com/118042/89583881-fcffce80-d7ef-11ea-9153-ac7836e97115.png)

**Comment by knaaptime** [comment] 2020-08-09 06:21
i think this should be resolved with the newest fix to tobler, but i need to double check

**Comment by knaaptime** [comment] 2020-08-11 18:23
i can confirm this is resolved with the latest dev version of tobler

**Comment by sjsrey** [comment] 2020-08-13 21:28
```python
import geosnap
```

    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 14779.08entries/s]
    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 18657.94entries/s]
    /usr/local/anaconda3/envs/pysal/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
      warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')



```python
geosnap.__version__
```




    '0.3.2'




```python
sd = geosnap.Community.from_census(county_fips='06073')
```

    /usr/local/anaconda3/envs/pysal/lib/python3.7/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
      return _prepare_from_string(" ".join(pjargs))



```python
import tobler
```


```python
tobler.__version__
```




    '0.3.1'




```python
from tobler.area_weighted import area_interpolate
```


```python
extensive = ['n_total_pop', 'n_total_housing_units', 'n_vacant_housing_units', 'n_black_persons', 'n_hispanic_persons' ]
intensive = ['median_household_income']
```


```python
gdfs = [sd.gdf[sd.gdf.year==year] for year in [1990,2000,2010]]
```


```python
sd1990, sd2000, sd2010 = gdfs
```


```python
extensive = ["n_total_pop"]
intensive = ['median_household_income']
```


```python
sd19902010 = area_interpolate(sd1990, sd2010, extensive_variables=extensive,
                intensive_variables=intensive)
```

    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values



```python
sd19902010.shape
```




    (627, 3)




```python
sd1990.shape
```




    (438, 195)




```python
sd2010.shape
```




    (627, 195)




```python
sd19902010.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>n_total_pop</th>
      <th>median_household_income</th>
      <th>geometry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3780.045461</td>
      <td>30027.580506</td>
      <td>POLYGON ((-117.01957 32.76373, -117.01562 32.7...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4109.068579</td>
      <td>27928.654437</td>
      <td>POLYGON ((-117.16864 32.74897, -117.16602 32.7...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3778.913865</td>
      <td>25588.558303</td>
      <td>POLYGON ((-117.14632 32.74842, -117.14250 32.7...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3127.204323</td>
      <td>16784.034521</td>
      <td>POLYGON ((-117.11577 32.75522, -117.11362 32.7...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4431.874144</td>
      <td>28626.872160</td>
      <td>POLYGON ((-117.37213 33.20012, -117.36902 33.2...</td>
    </tr>
  </tbody>
</table>
</div>




```python
sd20002010 = area_interpolate(sd2000, sd2010, extensive_variables=extensive,
                intensive_variables=intensive)
```

    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values



```python
sd20002010.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>n_total_pop</th>
      <th>median_household_income</th>
      <th>geometry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3882.981322</td>
      <td>40175.734975</td>
      <td>POLYGON ((-117.01957 32.76373, -117.01562 32.7...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4258.772452</td>
      <td>37318.052239</td>
      <td>POLYGON ((-117.16864 32.74897, -117.16602 32.7...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>4039.971454</td>
      <td>35394.196027</td>
      <td>POLYGON ((-117.14632 32.74842, -117.14250 32.7...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3873.042164</td>
      <td>20704.730669</td>
      <td>POLYGON ((-117.11577 32.75522, -117.11362 32.7...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5899.830878</td>
      <td>36428.660886</td>
      <td>POLYGON ((-117.37213 33.20012, -117.36902 33.2...</td>
    </tr>
  </tbody>
</table>
</div>




```python
sd20002010.n_total_pop.sum()
```




    2817686.995202498




```python
sd2000.n_total_pop.sum()
```




    2817687.0




```python
# now with geosnap
```


```python
sd_2010_gs = sd.harmonize(2010, extensive_variables=extensive,
                         intensive_variables=intensive)
```

    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/serge/Dropbox/p/pysal/src/subpackages/tobler/tobler/util/util.py:28: UserWarning: nan values in variable: median_household_income, replacing with 0
      warn(f"nan values in variable: {column}, replacing with 0")



```python
sd_2010_gs.gdf.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>geoid</th>
      <th>geometry</th>
      <th>median_household_income</th>
      <th>n_total_pop</th>
      <th>year</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>06073014901</td>
      <td>POLYGON ((-117.01957 32.76373, -117.01562 32.7...</td>
      <td>NaN</td>
      <td>4156.000000</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>1</th>
      <td>06073000300</td>
      <td>POLYGON ((-117.16864 32.74897, -117.16602 32.7...</td>
      <td>NaN</td>
      <td>4629.000000</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>2</th>
      <td>06073000800</td>
      <td>POLYGON ((-117.14632 32.74842, -117.14250 32.7...</td>
      <td>NaN</td>
      <td>3964.000000</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>3</th>
      <td>06073002201</td>
      <td>POLYGON ((-117.11577 32.75522, -117.11362 32.7...</td>
      <td>NaN</td>
      <td>3989.000000</td>
      <td>2010</td>
    </tr>
    <tr>
      <th>4</th>
      <td>06073018509</td>
      <td>POLYGON ((-117.37213 33.20012, -117.36902 33.2...</td>
      <td>NaN</td>
      <td>5325.999683</td>
      <td>2010</td>
    </tr>
  </tbody>
</table>
</div>




```python

```

**Comment by knaaptime** [comment] 2020-08-13 21:39
I cant reproduce this locally. With the latest development version of tobler (master on pysal/tobler) installed in my geosnap environment, I get the following

```python
import geosnap
```

    /Users/knaaptime/Dropbox/projects/geosnap/geosnap/_data.py:123: UserWarning: Unable to locate local census data. Streaming instead.
    If you plan to use census data repeatedly you can store it locally with the io.store_census function for better performance
      "Unable to locate local census data. Streaming instead.\n"
    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 7327.58entries/s]
    Loading manifest: 100%|██████████| 5/5 [00:00<00:00, 5726.79entries/s]



```python
sd = geosnap.Community.from_census(county_fips='06073')
```

    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
      return _prepare_from_string(" ".join(pjargs))



```python
extensive = ['n_total_pop', 'n_total_housing_units', 'n_vacant_housing_units']
intensive = ['median_household_income', 'p_poverty_rate']
```


```python
sd_2010 = sd.harmonize(2010,extensive_variables=extensive,
                      intensive_variables=intensive)
```

    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/util/util.py:28: UserWarning: nan values in variable: p_poverty_rate, replacing with 0
      warn(f"nan values in variable: {column}, replacing with 0")
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/util/util.py:28: UserWarning: nan values in variable: p_poverty_rate, replacing with 0
      warn(f"nan values in variable: {column}, replacing with 0")
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/area_weighted/area_weighted.py:253: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
    
      den = source_df["geometry"].area.values
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/util/util.py:28: UserWarning: nan values in variable: median_household_income, replacing with 0
      warn(f"nan values in variable: {column}, replacing with 0")
    /Users/knaaptime/anaconda3/envs/geosnap/lib/python3.7/site-packages/tobler-0.3.1-py3.7.egg/tobler/util/util.py:28: UserWarning: nan values in variable: p_poverty_rate, replacing with 0
      warn(f"nan values in variable: {column}, replacing with 0")



```python
sd_2010.gdf.plot('n_vacant_housing_units')
```




    <AxesSubplot:>




![png](output_4_1.png)



```python
sd_2010.gdf.plot('p_poverty_rate')
```




    <AxesSubplot:>




![png](output_5_1.png)



```python
sd_2010.gdf.plot('median_household_income').plot()
```




    []




![png](output_6_1.png)



```python

```


<img width="328" alt="output_4_1" src="https://user-images.githubusercontent.com/4213368/90189811-b4598f80-dd72-11ea-81b3-57e3ba258d27.png">
<img width="328" alt="output_5_1" src="https://user-images.githubusercontent.com/4213368/90189814-b58abc80-dd72-11ea-9874-b543376d0941.png">
<img width="328" alt="output_6_1" src="https://user-images.githubusercontent.com/4213368/90189815-b6235300-dd72-11ea-82b7-639fa82f5676.png">

**Comment by sjsrey** [comment] 2020-08-13 21:41
I did a clean clone of both geosnap and tobler for this. Could there be something in your geosnap that is not upstream?

**Comment by knaaptime** [comment] 2020-08-13 21:54
no i just installed it from master

```
cd geosnap; conda env create -f environment.yml
conda activate geosnap; python setup.py install
pip uninstall tobler -y  # uninstall conda version first 
cd ../tobler
python setup.py install  # install current master
```

**Comment by sjsrey** [comment] 2020-08-13 22:11
This is in a clean clone of geosnap after `conda env create -f environment.yml`
```
(base) ~/D/g/g/s/geosnap ❯❯❯ conda activate geosnap                                                                                                                                            
(geosnap) ~/D/g/g/s/geosnap ❯❯❯ python setup.py install                                                                                                                                        
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    with open("README.md", encoding="utf8") as file:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by sjsrey** [comment] 2020-08-13 22:13
What version of python do you have locally (since it isn't spec'd in the environment.yml file?)

**Comment by knaaptime** [comment] 2020-08-13 22:14
```
/Users/knaaptime/Dropbox/projects/geosnap master* ⇡ 19s
geosnap ❯ ipython
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by sjsrey** [comment] 2020-08-13 22:16
yah but there is no ipython in that environment.yml

**Comment by knaaptime** [comment] 2020-08-13 22:17
i had to install ipykernel manually so that jupyter would see it

**Comment by sjsrey** [comment] 2020-08-13 22:28
After starting completely over, as in fresh clones into new directories, and repeating these steps:

```
cd geosnap; conda env create -f environment.yml
conda activate geosnap; python setup.py install
pip uninstall tobler -y  # uninstall conda version first 
cd ../tobler
python setup.py install  # install current master
```

I'm still getting the nan for the intensive variables when using geosnap but not tobler.

**Comment by sjsrey** [comment] 2020-08-13 22:41
It turns out, plotting works even with nan values. So can you check the head to see if you are getting nans?

**Comment by sjsrey** [comment] 2020-08-13 22:43
<img width="1279" alt="Screen Shot 2020-08-13 at 3 42 29 PM" src="https://user-images.githubusercontent.com/118042/90194260-b247fe80-dd7b-11ea-84e0-b765aa1bc1bb.png">

**Comment by sjsrey** [comment] 2020-08-13 22:51
<img width="891" alt="Screen Shot 2020-08-13 at 3 50 29 PM" src="https://user-images.githubusercontent.com/118042/90194741-c8a28a00-dd7c-11ea-9400-ae21f6de7ad7.png">

Is something getting duplilcated?

**Comment by knaaptime** [comment] 2020-08-13 22:52
was just going through the smae thing. I have lots of nans but lots of values

need to look into the harmonize code closer

**Comment by knaaptime** [comment] 2020-08-13 22:53
was also wondering how the tests could be passing

**Comment by knaaptime** [comment] 2020-08-13 22:59
i think i see whats going on

**Comment by sjsrey** [comment] 2020-08-13 23:05
My hunch is it is in the geosnap harmonization as tobler warns it encountered NANs and has replaced them with 0s. So the nans we are seeing here are likely coming from some operation in the harmonize method.

**Closed** 2020-08-14 02:07 UTC
Labels: bug
